# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2f44aa7bf310e742cf6f502cddad809145fa0aedfc7f9ba3003eee186c563c21c9b872716e6af5576ff2761d7419224186ffbade16411c1278cb01df96cd75f

test:
  secret_key_base: 711946136b3c247ddc5b1a2e7852917b4b8c05c4872b1efee956f1f318049a3d0eec8b830e228f7cba789c276fecfb700d8bb1a725b596b118e2bd7ec088d8f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
